# Copyright 2026 Booz Allen Hamilton Inc.
# SPDX-License-Identifier: Apache-2.0
"""Default response processor implementation.

This module provides the default implementation of the ResponseProcessor protocol,
consolidating response transformation logic from orchestrator and response_handler.
"""

import logging
import time
from typing import Any

from foundry_agent_core import AgentRequest, AgentResponse, mask_session_id

logger = logging.getLogger(__name__)


class DefaultResponseProcessor:
    """Default implementation of ResponseProcessor protocol.

    Provides production-ready response processing with:
    - Multi-format response text extraction
    - Source and chunk extraction from agent metadata
    - Nuanced confidence scoring based on quality indicators

    For quality validation, use agent-evals scorers.
    """

    async def process_response(
        self,
        agent_response: Any,
        request: AgentRequest,
        start_time: float,
        query_id: str,
    ) -> AgentResponse:
        """Transform raw agent response into AgentResponse.

        Args:
            agent_response: Raw response from agent framework
            request: Original agent request
            start_time: Processing start time (for timing)
            query_id: Unique identifier for this query

        Returns:
            AgentResponse with content, processing time, and adapter metadata
        """
        processing_time_ms = (time.time() - start_time) * 1000

        # Extract response components
        response_text = self._extract_response_text(agent_response, query_id)
        sources, chunks_used = self._extract_sources_and_chunks(agent_response, query_id)

        # Calculate confidence score
        confidence_score = self._calculate_confidence_score(agent_response, response_text, sources, query_id)

        # Build AgentResponse with RAG fields in metadata
        result = AgentResponse(
            content=response_text,
            session_id=request.session_id,
            processing_time_ms=processing_time_ms,
            metadata={
                "sources": [s.model_dump() if hasattr(s, "model_dump") else s for s in sources],
                "chunks_used": [c.model_dump() if hasattr(c, "model_dump") else c for c in chunks_used],
                "confidence_score": confidence_score,
                "query_id": query_id,
                "original_query": request.query,
                "agent_metadata": self._extract_agent_metadata(agent_response),
            },
        )

        logger.debug(
            "Response processing completed",
            extra={
                "session_id": mask_session_id(request.session_id),
                "query_id": query_id,
                "response_length": len(response_text),
                "sources_count": len(sources),
                "chunks_count": len(chunks_used),
                "confidence_score": confidence_score,
            },
        )

        return result

    def _extract_response_text(self, agent_response: Any, query_id: str) -> str:
        """Extract and clean response text from agent response.

        Args:
            agent_response: Raw agent response object
            query_id: Query identifier for logging

        Returns:
            Cleaned response text
        """
        try:
            # Handle different Strands Agent response formats
            if hasattr(agent_response, "content"):
                response_text = str(agent_response.content).strip()
            elif hasattr(agent_response, "text"):
                response_text = str(agent_response.text).strip()
            elif hasattr(agent_response, "message"):
                response_text = str(agent_response.message).strip()
            elif isinstance(agent_response, str):
                response_text = agent_response.strip()
            else:
                response_text = str(agent_response).strip()

            # Clean response text
            response_text = self._clean_response_text(response_text)

            if not response_text:
                logger.warning(
                    "Empty response text extracted from agent",
                    extra={"query_id": query_id},
                )
                response_text = "No response generated by the agent."

            return response_text

        except Exception as e:
            logger.warning(
                "Failed to extract response text, using fallback",
                extra={"query_id": query_id, "error": str(e)},
            )
            return "Response processing error occurred."

    def _extract_sources_and_chunks(self, agent_response: Any, query_id: str) -> tuple[list[Any], list[Any]]:
        """Extract sources and chunks from agent response.

        Args:
            agent_response: Raw agent response object
            query_id: Query identifier for logging

        Returns:
            Tuple of (sources, chunks_used)
        """
        try:
            sources: list[Any] = []
            chunks_used: list[Any] = []

            # Extract sources
            if hasattr(agent_response, "sources"):
                sources = agent_response.sources or []
            elif hasattr(agent_response, "metadata") and isinstance(agent_response.metadata, dict):
                sources = agent_response.metadata.get("sources", [])

            # Extract chunks
            if hasattr(agent_response, "chunks"):
                chunks_used = agent_response.chunks or []
            elif hasattr(agent_response, "metadata") and isinstance(agent_response.metadata, dict):
                chunks_used = agent_response.metadata.get("chunks", [])

            logger.debug(
                "Extracted sources and chunks",
                extra={
                    "query_id": query_id,
                    "sources_count": len(sources),
                    "chunks_count": len(chunks_used),
                },
            )

            return sources, chunks_used

        except Exception as e:
            logger.warning(
                "Failed to extract sources/chunks",
                extra={"query_id": query_id, "error": str(e)},
            )
            return [], []

    def _calculate_confidence_score(
        self,
        agent_response: Any,
        response_text: str,
        sources: list[Any],
        query_id: str,
    ) -> float:
        """Calculate confidence score based on response quality indicators.

        Uses a nuanced scoring algorithm that considers:
        - Base confidence
        - Response text quality
        - Source availability and quality
        - Agent-provided confidence
        - Metadata quality flags

        Args:
            agent_response: Raw agent response
            response_text: Extracted response text
            sources: Extracted sources
            query_id: Query identifier for logging

        Returns:
            Confidence score between 0.0 and 1.0
        """
        try:
            confidence = 0.3  # Base confidence

            # Increase confidence based on response text quality
            if response_text and len(response_text.strip()) > 10:
                confidence += 0.2

            # Increase confidence if sources were used
            if sources:
                confidence += 0.3
                # Additional boost for multiple high-quality sources
                high_quality_sources = [
                    s for s in sources if hasattr(s, "similarity_score") and s.similarity_score > 0.8
                ]
                if len(high_quality_sources) > 1:
                    confidence += 0.1

            # Check if agent provided its own confidence
            if hasattr(agent_response, "confidence"):
                try:
                    agent_confidence = float(agent_response.confidence)
                    if 0.0 <= agent_confidence <= 1.0:
                        confidence = (confidence + agent_confidence) / 2
                except (ValueError, TypeError):
                    pass

            # Check for quality indicators in metadata
            if hasattr(agent_response, "metadata") and isinstance(agent_response.metadata, dict):
                metadata = agent_response.metadata
                if metadata.get("high_confidence", False):
                    confidence += 0.1
                if metadata.get("sources_verified", False):
                    confidence += 0.1

            # Ensure confidence is within valid range
            confidence = max(0.0, min(1.0, confidence))

            logger.debug(
                "Calculated confidence score",
                extra={
                    "query_id": query_id,
                    "confidence_score": confidence,
                    "response_length": len(response_text),
                    "sources_count": len(sources),
                },
            )

            return confidence

        except Exception as e:
            logger.warning(
                "Failed to calculate confidence score, using default",
                extra={"query_id": query_id, "error": str(e)},
            )
            return 0.5

    def _extract_agent_metadata(self, agent_response: Any) -> dict[str, Any]:
        """Extract metadata from agent response.

        Args:
            agent_response: Raw agent response

        Returns:
            Metadata dictionary with agent information
        """
        try:
            metadata: dict[str, Any] = {}

            if hasattr(agent_response, "metadata") and isinstance(agent_response.metadata, dict):
                metadata.update(agent_response.metadata)

            # Add execution information if available
            if hasattr(agent_response, "execution_time"):
                metadata["agent_execution_time"] = agent_response.execution_time

            if hasattr(agent_response, "tools_used"):
                metadata["tools_used"] = agent_response.tools_used

            if hasattr(agent_response, "reasoning"):
                metadata["agent_reasoning"] = agent_response.reasoning

            return metadata

        except Exception:
            return {}

    def _clean_response_text(self, response_text: str) -> str:
        """Clean and normalize response text.

        Args:
            response_text: Raw response text

        Returns:
            Cleaned response text
        """
        try:
            # Remove excessive whitespace while preserving paragraph breaks
            lines = response_text.split("\n")
            cleaned_lines = [" ".join(line.split()) for line in lines]
            cleaned_text = "\n".join(cleaned_lines)

            # Remove excessive newlines (more than 2 consecutive)
            while "\n\n\n" in cleaned_text:
                cleaned_text = cleaned_text.replace("\n\n\n", "\n\n")

            return cleaned_text.strip()

        except Exception:
            return response_text


def create_response_processor() -> DefaultResponseProcessor:
    """Factory function to create DefaultResponseProcessor instance.

    Returns:
        Configured DefaultResponseProcessor implementation
    """
    return DefaultResponseProcessor()
